services:
  olx-monitor:
    build: 
      context: .
      target: dev
    image: olx-monitor:latest
    restart: unless-stopped
    env_file: 
      - ./src/.env
    volumes:
      - ./src/.env:/usr/src/app/src/.env
      - ./src/config.js:/usr/src/app/src/config.js
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./package.json:/usr/src/app/package.json
      - ./data:/usr/src/app/data
    ports:
      - 3000:3000
    profiles:
      - develop